<?php
return [
    'toolbar'=>[
        'alignment',  // Displaying the proper UI element in the toolbar.
        'heading',
        '|',
        'bold',
        'italic',
        'link',
        'bulletedList',
        'numberedList',
        '|',
        'outdent',
        'indent',
        '|',
        'imageUpload',
        'blockQuote',
        'insertTable',
        'mediaEmbed',
        'undo',
        'redo'
    ],
    'plugins'=>[
        'Alignment',  // Adding the package to the list of plugins.
        'Autoformat',
        'BlockQuote',
        'Bold',
        'CloudServices',
        'Essentials',
        'Heading',
        'Image',
        'ImageCaption',
        'ImageStyle',
        'ImageToolbar',
        'ImageUpload',
        'Indent',
        'Italic',
        'Link',
        'List',
        'MediaEmbed',
        'Paragraph',
        'PasteFromOffice',
        'Table',
        'TableToolbar'
    ],
    'language'=>'en',
    'image'=>[
        'toolbar'=>[
            'imageTextAlternative',
            'toggleImageCaption',
            'imageStyle:inline',
            'imageStyle:block',
            'imageStyle:side'
        ]
    ],
    'table'=>[
        'contentToolbar'=>[
            'tableColumn',
            'tableRow',
            'mergeTableCells'
        ]
    ]
];